### ISSUE TITLE
crash startup ?

### ISSUE THREAD

**Issue by theChronodonut1337** [uujuju1/Radio#1]
[crash-report-06_03_2024_15_33_51.txt](https://github.com/user-attachments/files/15530333/crash-report-06_03_2024_15_33_51.txt)
java.lang.RuntimeException: ah yes
	at radio.core.RadioSoundControl.lambda$musicNames$1(RadioSoundControl.java:83)
	at arc.struct.Seq.each(Seq.java:189)
	at radio.core.RadioSoundControl.lambda$musicNames$2(RadioSoundControl.java:79)
	at arc.struct.Seq.each(Seq.java:189)
	at radio.core.RadioSoundControl.musicNames(RadioSoundControl.java:79)
	at radio.core.RadioSoundControl.<init>(RadioSoundControl.java:14)
	at radio.RadioMod.lambda$new$0(RadioMod.java:14)
	at arc.Events.fire(Events.java:53)
	at arc.Events.fire(Events.java:43)
	at mindustry.ClientLauncher.update(ClientLauncher.java:224)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)
Caused by: arc.util.ArcRuntimeException: Error loading music: C:\Users\Koji\AppData\Local\Temp\dark__0
	at arc.audio.Music.load(Music.java:68)
	at arc.audio.Music.<init>(Music.java:39)
	at radio.core.RadioSoundControl.lambda$musicNames$1(RadioSoundControl.java:81)
	... 13 more
Caused by: arc.util.ArcRuntimeException: File not found
	at arc.audio.Soloud.streamLoad(Native Method)
	at arc.audio.Music.load(Music.java:60)
	... 15 more
crash reported

**Comment by uujuju1** [comment]
i'm not really working on the mod anymore
